version: '2'
services:
  mysql:
    image: mysql:5.7
    environment:
     - MYSQL_ROOT_PASSWORD=1234
     - MYSQL_DATABASE=tour_db
    ports:
      - "3306:3306"
  tour_agency:
    image: tour_agency
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    restart: always